### PR TITLE
Fixes app ignoring configured hostname

### PR DESCRIPTION
**Pull request by Deprofets**
By default the app listens on all available interfaces, ignoring the configured hostname

### CODE REVIEW

**Comment by daffl** [comment]
Thank you!

**Comment by daffl** [comment]
Unfortunately it looks like we have to revert this since many cloud providers (verified with at least Azure and Heroku) do not work properly when listening on the configured hostname.

**Comment by Deprofets** [comment]
Using "::" as the default host or removing "host" from the configuration
files should work for such cases. Both work for Heroku but I haven't had
the chance to test this on Azure, perhaps we could set this as the default
hostname after confirming?

**Comment by Deprofets** [comment]
Using "::" as the default host or removing "host" from the configuration files should work for such cases. Both work for Heroku but I haven't had the chance to test this on Azure, perhaps we could set this as the default hostname after confirming?

**Pull request merged**
