### PR TITLE
Remove confusing and unnecessary name parameter

### PR DESCRIPTION
**Pull request by daffl**
Closes https://github.com/feathersjs-ecosystem/feathers-knex/issues/150

### CODE REVIEW

**Comment by eric-burel** [comment]
Hi, thanks for your quick reaction to this issue, but I did not get what your changes imply? How should I set the table name now?

**Comment by daffl** [comment]
None of the service adapters other than Knex require a table name. The issue with Knex tables was that the name should have been using `snakeCase` instead of `kebabCase`. You shouldn't have to set anything explicitly and all the other names are explicitly given in the `*.service.js` files. Service name is what is passed to `app.use('/<name>`)` table name is what is passed as `name` to the Knex adapter. There is no magical relation between the two whatsoever other than what is defined in the code.

**Comment by eric-burel** [comment]
Hi, I am still not sure about this pattern. Here is my use case: I work with a complex SQL Server db. It is provided by my client, it is meant to help analysing other databases. So there are namespaced tables, with long names.
I chose Knex because it is a low level solution, so it's good if I ever need complex request.

Right now:
- the table name is in 2 places, the model and the service. That's 2 sources of truth :/
- name is still not a very good name for the option, should definitely be `tableName` to avoid misunderstanding
- often, you'll want to change the table name. Using `snakeName` as the default is a good idea since often you both create the table and connect to it through a service, but imo we should be able to change it while generating the service, because you'll often work with existing tables too.

I know those are definitely not big issues nor urgent ones. If you confirm this is doable and make sense I may try to PR to give some help.

**Comment by daffl** [comment]
Sure, we can add an alias from `name` to `tableName` to the Knex adapter. Since Knex doesn't really have models per se though, using its name is not two sources of truth, it is the only way to identify which table the adapter is supposed to use.

I prefer not to add (esp. db specific) prompts to the generator for fairly simple things that just require a minor code change to change it according to your requirements.

**Pull request merged**
