### PR TITLE
Migrate generated app to be usable without Babel and Node 5 directly

### LINKED ISSUE #31: Possibly remove Babel from generated app
I just did some tests and I think Node 5 now pretty much supports all ES6 features that we are using in the docs and the generator except for modules (which actually isn't part of the ES6 spec anyway).

Since @marshallswain already noticed slower app startup time and higher memory consumption using Babel I am proposing to just switch the generator and all documentation examples to `require` imports and syntax that is supported by latest Node.

### PR DESCRIPTION
**Pull request by daffl**
This pull request removes the Babel dependency, moves back to CommonJS module syntax and uses Node 5's ES6 features directly. Closes #31

### CODE REVIEW

**Comment by daffl** [comment]
This now also include a basic generator test and should be good to merge.
/cc @ekryski

**Comment by ekryski** [comment]
:+1: Just going to pull it down right now and test it out.

**Comment by ekryski** [comment]
I pulled it down and tested with a few of the dbs. I didn't try all of them but it looks good. :shipit:

**Comment by kulakowka** [comment]
When will it be published in the NPM? Or tell me how I can test new generator without installing via npm?

**Comment by ekryski** [comment]
@kulakowka We'll probably publish a new version later today or tomorrow. We have a whole bunch of updates coming to the generator.

**Pull request merged**
