### PR TITLE
Tweak the `timestamp` in mongoose model template

### PR DESCRIPTION
**Pull request by Mr-Binary**
No test case added, hope it's fine for a template file -_-

### CODE REVIEW

**Comment by marshallswain** [comment]
This looks like a good change.  I'm not able to see why the tests are failing.  Do they pass for you locally?

**Comment by Mr-Binary** [comment]
I tried it before, always stuck somewhere, it's not failed, it's just timeout.
If I remember it right, the tests are not passing even before I added the code.

**Comment by daffl** [comment]
@Mr-Binary Try pulling down latest master. Looks like the failing tests were because of the latest version of Mocha which got installed automatically which was fixed in #283

**Comment by Mr-Binary** [comment]
@daffl Thanks, I updated my local repo, and open mongodb, now 16 tests pass and 2 pending.

```bash
........
├─ tar-pack@3.4.0
├─ tar@2.2.1
├─ uid-number@0.0.6
└─ wide-align@1.1.2
✨  Done in 6.71s.
      ✓ sequelize (13859ms)
      - rethinkdb
    feathers:authentication
      - runs and initializes working local strategy


  16 passing (4m)
  2 pending

albert:generator-feathers albertgao$
```

Is this good?

And, there is a package-lock.js generated in my local folder, do I need to commit that as well?

Besides, we should let people they need to start their local `mongod` at the default port to let the tests going, otherwise, they need to wait until the 1st round failed then know why. what do you think? :)

**Comment by daffl** [comment]
Looks great, thank you again!

**Comment by Mr-Binary** [comment]
No worries. Wish I could contribute more to this project, I deadly love this framework. 🍡

**Pull request merged**
