### PR TITLE
Fix import in types/knex.ts

### PR DESCRIPTION
**Pull request by ucokfm**
`const { Service, KnexServiceOptions } = require('feathers-knex');` prevent ts compile

### CODE REVIEW

**Comment by daffl** [comment]
Oops, thanks! Actually wondering why the tests are passing then since Knex should be tested via https://github.com/feathersjs/generator-feathers/blob/master/test/generators.test.js#L81

**Comment by ucokfm** [comment]
It seems jest and mocha is not doing type checking while testing.
We can use their forks: [ts-jest ](https://github.com/kulshekhar/ts-jest) and [ts-mocha](https://github.com/piotrwitek/ts-mocha),
or alternatively use `tsc --noEmit` for additional type checks

**Comment by daffl** [comment]
Could tslint handle that, too?

**Comment by daffl** [comment]
Or we just add an `npm run compile` step before running the tests I guess.

**Pull request merged**
