### PR TITLE
updating error handler to be more HTML friendly

### PR DESCRIPTION
**Pull request by ekryski**
I've removed the `404.html` page and renamed the `500.html` page to `error.html`.

The error handler now redirects to `/error` which, renders the `error.html` page and uses JavaScript to parse the error code and message from the query string. The default code and message is the 404 page so there is also a vanity route `/404`.

So it will now show all errors and not just a 500. Much more user friendly.

### CODE REVIEW

**Comment by daffl** [comment]
Why did this need to be changed? I'm not sure if error redirects are the best solution. The server and the browser loose all context and there is no way to know where that error came from to e.g. print a stack trace or send an error report.

**Comment by ekryski** [comment]
Without adding a template engine to the mix, this is the only way to get the actual error messages and codes onto the error page. Having just a 500 and 404 wasn't good enough because a bunch of different errors could occur and if it wasn't a 404 it would just show a 500. Which is confusing.

The stack traces still get logged, and if it is a JSON response, get sent in development mode. You can also send error reports by just adding a middleware before the error handler.

We can revert if need be and I'm open to other ideas but I think this is a better solution than what was previously there.

**Comment by daffl** [comment]
What I am wondering is if this should be pre-generated or something everybody should take care of themselves. Basically my assumption with the old setup was that if you do not use a view engine it is very unlikely that anybody will ever hit an error other than a 404 in the browser.

Without a view engine you're probably running an API only server (maybe with a public folder for your frontend). Personally I wouldn't give more information other than a general error page to a user that tries to hit your API endpoints directly in the browser.

**Comment by ekryski** [comment]
@daffl fair points. My only concern really, and this is where the confusion came from, is authentication errors. Currently if you hit an endpoint that requires validation you get a 500.html, which is very confusing.

For the most part you have convinced me to revert, but maybe we should also have a 401.html?

**Comment by daffl** [comment]
I was thinking we could create an `errors/` folder where you can add pages by status code and it'll serve that. But maybe just adding a 401.html is best. If you want better browser error handling than plain HTML pages you'll probably change the error middleware to use a view engine anyway.

**Pull request merged**
