### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kulakowka**
Add information about installation, usage and available generator commands to README.md

### CODE REVIEW

**Comment by daffl** [comment]
Makes sense, thank you!

**Comment by marshallswain** [comment]
Is this in the new docs anywhere? I couldn't find it

**Comment by ekryski** [comment]
@marshallswain Only in quick start section. Maybe when we eventually roll a Feathers CLI we'll give it it's own.

**Comment by marshallswain** [comment]
Cool! You guys have done a lot of work.

**Pull request merged**
