### PR TITLE
feat(ts): add support for @typescript-eslint

### PR DESCRIPTION
**Pull request by fratzinger**
- add function return types
- add @typescript-eslint to package & eslintrc.json
- add comments `eslint-disable-next-line @typescript-eslint/...`
- add script `lint` back to `package.json`
- add `@types/cassanknex`
- remove dynamic imports & remove require('') in *.ts
- add missing devDependencies for generator

### CODE REVIEW

**Comment by daffl** [comment]
Phew, I almost thought I broke your pull request and blew away the history but I found the commit and resubmitted it in https://github.com/feathersjs/generator-feathers/pull/541. Thank you for doing this! It will go out shortly (just have to merge with latest).

**Comment by fratzinger** [comment]
great :) I'm proud that it finds its way :)

**Comment by daffl** [comment]
Also, sorry it took so long.

**Comment by fratzinger** [comment]
Nono, it's all good. With this amount of packages it's difficult to keep track of the PRs, I can imagine. No pressure on this one.

**Pull request closed without merging**
