### PR TITLE
Namespace support using dot notation

### PR DESCRIPTION
**Pull request by richbai90**
#341 Support name spacing with . notation. All tests are passing except the new ones I added, I am not sure why those are not passing, but a manual test shows the logic is sound. With some guidance I can update the tests so that they pass also.

### CODE REVIEW

**Comment by richbai90** [comment]
@daffl Travis CI is failing because of the new tests that I wrote. Can you help me see why these are failing? It doesn't seem to be an issue with the endpoint, it fails before ever attempting to send a request.

**Comment by richbai90** [comment]
Nevermind, after some more debugging I figured it out. Tests should all pass now.

**Comment by daffl** [comment]
Thank you for doing this @richbai90. Is there a reason you decided to use dot notation instead of normal path separators? It could make things a little easier right?

The basic issue at the moment is that something like

```
/v1/my/users
```

Will generate a service name like `v1-my-service` and instead we want it do be in the `v1/my/users` folder right?

**Comment by richbai90** [comment]
Yeah, I actually don't know why I used . Separation, except that that's what I decided to go with when I started noticing the code. Path separation makes more sense, I'll make the adjustments.

**Comment by richbai90** [comment]
I am really busy ATM. I need this change for a project I'm working on, but it's taken a back seat for a minute. I'll get to it as soon as I can, or you can too. Either way.

**Pull request closed without merging**
