### PR TITLE
[Do not merge] More lighthouse improvements

### PR DESCRIPTION
**Pull request by bravo-kernel**
- [x] adds html doctype to increase Best Practices to 100
- [x] adds viewport meta tag to improve SEO. The page looks awesome on mobile too now.
- [x] adds decription meta tag to improve SEO
- [x] ~change color to more contrast for 100% Accessibility score OR~ make link color identical to the green used on the documentation website

### CODE REVIEW

**Comment by bravo-kernel** [comment]
image

Almost there, would you please review the text I added to the content meta tag (copied from the docs website).  

Also, if we want the full 100% for accessibility the currently green link-color needs to be changed to something with more contrast. For instance also use `#333` but font-weight `bold` (sample below). I can imagine you do not want to sacrifice that, let me know. Regardless of the lighthouse score.. IMO we should change the current green to the green used on the documentation site to keep things consistent. What do you think.

image

> ps: with the viewport the page now looks awesome on mobile too 💃

**Comment by bravo-kernel** [comment]
@daffl I have updated the link color to match the documentation website. Unless you want to go 100% (and thus change the link color) this should be good to merge.

**Comment by daffl** [comment]
This looks good, thank you. Can you pull latest master to resolve the conflicts?

**Comment by bravo-kernel** [comment]
Done :shipit:

**Comment by daffl** [comment]
Great, thank you!

**Comment by bravo-kernel** [comment]
You’re welcome

**Pull request merged**
