### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by ekryski**
This PR

- Adds a basic winston logger back in (that is my recommended production logger)
- Adds helmet for security by default
- Exposes the secret generator to the CLI

### CODE REVIEW

**Comment by daffl** [comment]
Do we really want the logger middleware though? I was thinking we should do basic logging through `app.hooks` [in app.js](https://github.com/feathersjs/generator-feathers/blob/master/generators/app/templates/app.js).

**Comment by daffl** [comment]
Something like

```js
const log = require('winston');

app.hooks({  
  error(hook) {
    log.error(`Error in '${hook.path}'' calling '${hook.method}' method', hook.error);
  }
})
```

**Comment by ekryski** [comment]
You might want both I guess. If you had custom routes but yeah I'm down with that as a default instead. Should we just auto-gen a logger hook and include that in the `app.js` file?

**Comment by ekryski** [comment]
Looks good! :shipit:

**Pull request merged**
