### PR TITLE
Adding generator support for NoSQL schemas

### PR DESCRIPTION
**Pull request by Jaden-Giordano**
Uses feathers-schema to generate a schema for json entries in a NoSQL database. Generates on top of a service, populates the hooks and creates the schema template as ```<service>.schema.js```.

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
```
/home/travis/build/feathersjs/generator-feathers/generators/schema/index.js
  36:79   error  Unnecessary escape character: \'  no-useless-escape
  36:113  error  Unnecessary escape character: \'  no-useless-escape
```

**Comment by marshallswain** [comment]
@Jaden-Giordano thanks for this!!!  Is there any documentation to go along with this?

**Comment by Jaden-Giordano** [comment]
Yeah im going to be putting some documentation together, its already mostly documented i just need to give a few steps to get started with it then link to the docs of the person who created the feathers-schema node package.

**Comment by daffl** [comment]
What is the difference between `feathers-schema` and the [validateSchema](https://docs.feathersjs.com/api/hooks-common.html#validateschema) common hook?

Our current approach was that the generator should try and avoid adding Feathers specific dependencies that are not part of core until we have a good way of supporting plugins.

**Comment by Jaden-Giordano** [comment]
The validateSchema common hook is extremely similar. Not sure if this is completely viable considering that, I totally didn't see that hook. This should probably be closed in that light.

**Comment by daffl** [comment]
Changing to the validateSchema hook was what I was going to suggest. I like the idea of adding some basic schema validation, if we can do that without adding another dependency even better.

**Comment by daffl** [comment]
Any news on this? I don't just want to close it but we have to keep our issues and PRs curated if there hasn't been much activity.

**Comment by Jaden-Giordano** [comment]
I'm going to close this for now and then I'll create a new pull request or reopen this one when I have a chance to make those changes.

**Pull request closed without merging**
