### PR TITLE
general improvement suggestions

### PR DESCRIPTION
**Pull request by mastertinner**
@daffl, please have a look at my suggestions and let me know what you think about them. Also, please let me know if we can/must raise the `engines.node` version in `package.json` to `'>= 4'` because we use `const` and `let`.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you! I'll hopefully have some time to check it out later tonight. At first glance it all looks very reasonable so once we get the tests passing we can cut a new generator release and then look at how to incorporate those changes into the new generator.

**Comment by mastertinner** [comment]
@daffl, do you know why the build for Node 4 shows `Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in /home/travis/build/feathersjs/generator-feathers/generators/app/templates/service.js while compiling ejs`? There's a `'use strict';` statement in the first line of that file... As stated above, I took the liberty to remove the support for Node 0.12. I hope that's in your best interest.

**Comment by ekryski** [comment]
Thanks for the PR @mastertinner. Unfortunately for right now we need to keep node 0.12 support. We'll be dropping that support in Jan 2017. If you can get the tests passing then we should be good. We might be able to run the tests with the babel compiler to see if that fixes the build.

**Comment by daffl** [comment]
Thanks again @mastertinner and sorry this stayed open for so long. We just merged #159 which is a pretty major overhaul where I also took some of the changes from your PR. It has been released as v1.0.0-pre.1 and `feathers-cli@pre`.

Closing this pull request since master has diverged quite a bit by now but let us know if you find anything that can be improved in the current version.

**Pull request closed without merging**
