### PR TITLE
Add a dev script with nodemon as a watcher (#385)

### LINKED ISSUE #385: dev mode with watcher
Moving to the appropriate repo: https://github.com/feathersjs/cli/issues/163

### PR DESCRIPTION
**Pull request by Alfredo-Delgado**
Tested locally:
- `npm i feathers-cli`
- `npm link generator-feathers`
- `npx feathers generate app`
- `npm run dev`
- `touch package.json`

Resolves #385

### CODE REVIEW

**Comment by daffl** [comment]
Sweet, thank you. Will go out with the next version.

**Comment by DaddyWarbucks** [comment]
I noticed this ticket from the slack channel and think it is a great addition!
I also include this script in my personal projects `"debug": "DEBUG=* nodemon src/",`.

I will add my whole `scripts` below, although they may be a little more opinionated than needed/wanted
```
"scripts": {
    "start": "node src/",
    "watch": "nodemon src/",
    "debug": "DEBUG=* nodemon src/",
    "mocha": "mocha test/ --recursive --exit",
    "lint": "eslint src/. test/.",
    "fixcode": "eslint src/. test/. --fix",
    "test": "npm run lint && npm run mocha",
    "prepush": "npm run test"
  },
```

**Comment by Alfredo-Delgado** [comment]
My two cents:

- instead of a debug script, I'd `DEBUG=* npm run dev` (`dev` matches your `watch` script), the benefit of environment variables is that the same scripts can behave differently based on the environment
- instead of a fix script, I'd `npm run lint -- --fix`, similar benefits of not having to duplicate the base script to enable a switch

**Comment by DaddyWarbucks** [comment]
Good points. 
I agree on your first point, it should just call the dev/watch script directly vs reproducing it. 

On the second point, I would personally rather have a second script than just calling the `lint` script with another flag. It is easier for me to tell my jr devs "just run the `fixcode` script" rather than telling them _how_ to run another script. It also makes the scripts more composable, for example it is more easily combined in the `test` script. But, I do not have strong opinions on it, really. I see your point as well.

It may also be helpful to add some additional debug scripts to illustrate what that is actually doing.
`debug:feathers: DEBUG=feathers npm run dev` and `debug:something: DEBUG=something npm run dev`

**Comment by daffl** [comment]
I always run my linting scripts with `--fix` but I'd rather have the generator be less opinionated about these things and just run the standard commands. Wondering if it might help to document the `DEBUG` flag a little more.

**Comment by DaddyWarbucks** [comment]
^^ I just edited my comment above as your comment came in, basically saying the same thing about `DEBUG`. I think some more documentation around `DEBUG` would be helpful.

**Comment by Alfredo-Delgado** [comment]
I'm a fan of having [prettier](https://prettier.io) configured to automatically normalize syntax formatting. :) That goes further afar of opinions feathers should be pushing, though :)

**Comment by DaddyWarbucks** [comment]
Same. I have it setup in my eslint file to handle prettier there also. But that is too opinionated for the CLI. I will post mine for posterity if anyone stumbles across this thread.
```
{
  "env": {
    "es6": true,
    "node": true,
    "mocha": true
  },
  "parserOptions": {
    "ecmaVersion": 8,
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "extends": ["eslint:recommended", "plugin:prettier/recommended"],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "trailingComma": "none",
        "singleQuote": true
      }
    ],
    "no-unused-vars": [
      "warn",
      {
        "argsIgnorePattern": "data|params|reject"
      }
    ],
    "no-console": ["warn"]
  }
}
```

**Pull request merged**
