### PR TITLE
Add Auth0 to OAuth providers

### PR DESCRIPTION
**Pull request by marshallswain**

### CODE REVIEW

**Comment by daffl** [comment]
Doesn't Auth0 do other things than OAuth as well? Also, should we add a bunch of other common strategies as well?

**Comment by marshallswain** [comment]
There are four different auth methods with Auth0.  This one takes no additional work right now.  Auth0 is the only one I've seen requested, so maybe we can get this shipped and add others later.

**Comment by daffl** [comment]
Sounds good. :shipit:

**Comment by marshallswain** [comment]
Released as `generator-feathers@1.2.8`

**Comment by kristianmandrup** [comment]
Do you have an example feathers app demonstrating the latest Auth0 integration?
I'll be working on one here: https://github.com/tecla5/easy-graphql-auth/tree/master/packages/feathers-app

**Comment by marshallswain** [comment]
I don't have an example published at the moment, but it's the same as the [Basic OAuth Guide](https://docs.feathersjs.com/guides/auth/recipe.oauth-basic.html).

**Comment by harijoe** [comment]
@marshallswain It would be very nice to have an Auth0 example, I am struggling at making it work by just following the OAuth guide as there are a lot of things to configure when using auth0.

**Pull request merged**
