### PR TITLE
Included the use strict statement on the logger file

### PR DESCRIPTION
**Pull request by kaiquewdev**

### CODE REVIEW

**Comment by daffl** [comment]
I removed the `use strict;` statements from all generated files since we only needed it for the `class` syntax in Node 4. Since the generator now only supports v6 which has classes and ESLint - unlike JSLint - does not complain about it.

**Comment by daffl** [comment]
Does that make sense? I could be totally missing something...

**Comment by eddyystop** [comment]
I believe including a "use strict" is still considered best-practices.

**Comment by daffl** [comment]
The reason I took it out is because using the Flow parser code transformation we changed to in https://github.com/feathersjs/generator-feathers/pull/207 is breaking Linting (for some reason it adds an additional semicolon to `'use strict;'` statements).

The only way to bring it back would be to go back to using Babel 5 as the parser which gives a pretty ugly error message when installing `feathers-cli`.

**Comment by kaiquewdev** [comment]
[pipelineLog-{5462a63f-a92b-44c1-9be7-3e072150ac04}.txt](https://github.com/feathersjs/generator-feathers/files/956788/pipelineLog-.5462a63f-a92b-44c1-9be7-3e072150ac04.txt)

**Comment by kaiquewdev** [comment]
Has failed on Bitbucket Pipelines.

**Comment by daffl** [comment]
The log is showing Node v4.6.0 which is no longer supported by this version of the generator. As we talked about in Slack, updating the pipeline to a newer Node version should fix it. Thanks for the PR though!

**Comment by kaiquewdev** [comment]
I feel happy with your transparency, this puts the another on a high level of quality. Thank you for your response.

**Pull request closed without merging**
