### PR TITLE
Use AST transformations to import generated services and hooks

### LINKED ISSUE #29: auto configuring of service is brittle
The Regex for where the `app.configure(service)` call is injected is breaking with some databases (Postgres) because of how we are testing for `}`.

It works with Mongo, NeDB, etc.

### LINKED ISSUE #46: Importing hooks are brittle
They currently break when you have existing hooks on multiple lines.

### LINKED ISSUE #47: Convert regex replacement to AST
Regex's are super brittle for inserting code. Instead @daffl laid some of the groundwork for converting over to using an AST to transform the generated code with #43.

This will help close out #2, #29, #46.

### PR DESCRIPTION
**Pull request by daffl**
This pull request uses the AST transformations to import new services and hooks. This should make importing much more solid and also throw more descriptive errors when the code changed so much that adding the code is not possible.

Closes #47, closes #46, closes #29

### CODE REVIEW

**Comment by daffl** [comment]
The tests are still not great though.

**Comment by ekryski** [comment]
Oh I didn't see this earlier. I'll take a look in 30 minutes.

**Comment by daffl** [comment]
Generated app, services and hooks are now being tested as well.

**Comment by ekryski** [comment]
tested locally with a bunch of dbs. :shipit:

**Pull request merged**
