### PR TITLE
Updated logging component to work with latest Winston version.

### PR DESCRIPTION
**Pull request by plunkettscott**
The latest version of Winston does not work without specifying transports. This PR pulls the winston component into it's own file (logger) and is imported where logging is necessary.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request. Two things:

1. What happens without those changes? Does this mean #363 (the Greenkeeper PR for the major version) should have actually failed (if so, I have to check why it passed)?
2. Could you re-submit or update the PR to not include any code formatting changes. It makes it really hard to see what actually changed.

**Comment by plunkettscott** [comment]
Sure can. I honestly didn’t realize that the code formatted. I disabled it on the workspace prior. I’ll fix that. 

As for what happens, you get a message in the console that says something to the extent of “Tried to write to log with no transport” because Winston was bumped to v3 (which was the “next” release prior).

I don’t think any tests are checking the console output. The actual app doesn’t fail to start, it just creates unnecessary noise in the console.

**Comment by daffl** [comment]
I just noticed that in the `feathers-chat`. If you can get the PR in without the formatting we can definitely get this out soon.

**Comment by plunkettscott** [comment]
Closing this PR as I am about to submit a new one with a change to the logger hook (to avoid confusion between what each is doing) and removed code formatting.

**Pull request closed without merging**
